[package]
name = "ciid"
version = "0.1.0"
authors = ["Pablo Sichert <mail@pablosichert.com>"]
edition = "2018"

[dependencies]
clap = "2.33"
chrono = "0.4"
image = "0.22"
rawloader = "0.36"
regex = "1.3"
sha2 = "0.8"
