[package]
name = "ciid"
version = "0.1.0"
authors = ["Pablo Sichert <mail@pablosichert.com>"]
description = """
Utility to derive a chronologically sortable, unique identifier for images.

The first part of the identifier encodes the creation date of the image (48 bit timestamp encoded in 12 characters), while the second part is a hash (256 bit hash encoded in 64 characters) based on the contents of the image buffer.

The encoded characters in the output string are in the range of [a-p].

Example for a resulting identifier: abcdefgijklm-opabcdefgijklmopabcdefgijklmopabcdefgijklmopopabcdefgijklmopabcd."""
edition = "2018"

[dependencies]
bindgen = "0.52.0"
clap = "2.33"
chrono = "0.4"
image = "0.22"
regex = "1.3"
sha2 = "0.8"

[build-dependencies]
bindgen = "0.52.0"
