name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1.0.5
      - name: Install ExifTool
        run: |
          source ./bin/install.sh
          install_exiftool
      - name: Install LibRaw
        run: |
          source ./bin/install.sh
          install_libraw
      - name: Cargo test
        run: cargo test
